model:
  cfg_path: ./config/sr_sr3_256_512_Chest.json
data:
  root: ./test_data/Chest
  input_folder: low
  cond_folder: lr_dn
  output_folder: hr_dn
  target_folder: full
  res: 512
  len: -1
diffusion:
  ddim: True
  ddim_eta: 1.0
dn:
  # mode==0: ConsLam
  # mode==1: AdaLamI 
  # mode==2: AdaLamII
  # mode==3: AdaLamI&II
  mode: 3
  lam0: 0.09 # ConsLam: $\lambda_t=\lambda_0\cdot\sqrt{\bar{\alpha}_t}$
  a: 3.5
  b: -0.09 # AdaLamI: $\lambda_0^{ada} = a \cdot std(\widehat{n}) + b$
  c: 1.2 # AdaLamII: $\Lambda_0^{ada} = c \cdot \widehat{n}$
  resume: 3
  mean_num: 10 # multiple denoising and take average, reduce mean_num if CUDA_OUT_OF_MEMORY
  bs: 1 # batch size
